stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project experiments.xcodeproj -scheme experiments | xcpretty
    - xcodebuild test -project experiments.xcodeproj -scheme experiments -destination 'platform=iOS Simulator,name=iPhone XÊ€,OS=12.2' | xcpretty -s
  only:
    - develop
  tags:
    - test
