stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project citest.xcodeproj -scheme citest | xcpretty
    - xcodebuild test -project citest.xcodeproj -scheme citest -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.1' | xcpretty -s
  tags:
    - test
